fixtures:
  repositories:
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    concat: "https://github.com/puppetlabs/puppetlabs-concat.git"
    yum: "https://github.com/voxpupuli/puppet-yum.git"
    collectd: "https://github.com/Yuav/puppet-collectd.git"
  symlinks:
    lysaker_monitored: "#{source_dir}"
