name          'puppet-lysaker_monitored'
version       '0.1.0'
source        ''
author        'puppet'
license       'Apache 2.0'
summary       ''
description   ''
project_page  ''

dependency 'puppetlabs/stdlib'
